apimServiceName: apim-contoso-demo-mijohns-qa
namedValues:
  - name: ResourceGroupSecret
    properties:
      displayName: ResourceGroupSecret
      value: "{#ResourceGroupSecretValue#}"
  - name: APIMInstanceSecret
    properties:
      displayName: ResourceGroupSecret
      value: "{#APIMInstanceSecretValue#}"