openapi: 3.0.1
info:
  title: API-NIKE-INDIRECT-GOODS-RECEIPT
  description: ''
  version: '1.0'
servers:
  - url: https://apim-contoso-demo-mijohns.azure-api.net
paths:
  /:
    post:
      summary: indirectgoodsreceipt
      description: indirectgoodsreceipt
      operationId: indirectgoodsreceipt
      responses:
        '200':
          description: 'null'
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]